### ISSUE TITLE
How to calculate A

### ISSUE THREAD

**Issue by kokitsuyuzaki** [wanwenzeng/coupleNMF#3]
Hi,

After reading your paper, I am interested in this method.
https://www.pnas.org/content/115/30/7723

I thought it was very advanced as a way to integrate two matrices that have neither rows nor columns in common.

By the way, the matrix A (Peak×Gene) in Equation (1) seems to be a pre-calculated matrix in this implementation , but what kind of calculation do you do to get it?
https://github.com/wanwenzeng/coupleNMF/blob/116a5d4f53f6fb3dd2674b278943ad65f021c06e/coupleNMF.py#L44

I'm not familiar with the problem of penalized least-squares in equation (3), and I was wondering what kind of solver is used to solve it.
In particular, since the Frobenius norm contains a summation symbol, it seems to me that this model is different from general linear regression.

**Comment by wanwenzeng** [comment]
It is calculated using PECA https://www.pnas.org/content/114/25/E4914.
If you have HiChIP data, you can also use HiChIP as A and use DC3 https://www.nature.com/articles/s41467-019-12547-1.


> Hi,
> 
> After reading your paper, I am interested in this method. https://www.pnas.org/content/115/30/7723
> 
> I thought it was very advanced as a way to integrate two matrices that have neither rows nor columns in common.
> 
> By the way, the matrix A (Peak×Gene) in Equation (1) seems to be a pre-calculated matrix in this implementation , but what kind of calculation do you do to get it?
> 
> https://github.com/wanwenzeng/coupleNMF/blob/116a5d4f53f6fb3dd2674b278943ad65f021c06e/coupleNMF.py#L44
> 
> I'm not familiar with the problem of penalized least-squares in equation (3), and I was wondering what kind of solver is used to solve it. In particular, since the Frobenius norm contains a summation symbol, it seems to me that this model is different from general linear regression.

**Comment by kokitsuyuzaki** [comment]
Thanks!
I'll check these papers.
